name: expandable_quadtree
description: A flexible and efficient Quadtree implementation for Flutter and Dart, perfect for spatial indexing, collision detection, and organizing large sets of 2D data. This package supports multiple quadtree configurations, including expandable, horizontally expandable, and vertically expandable quadtrees.
version: 0.1.0
repository: https://github.com/Jei-sKappa/expandable-quadtree-dart
issue_tracker: https://github.com/Jei-sKappa/expandable-quadtree-dart/issues
documentation: https://github.com/Jei-sKappa/expandable-quadtree-dart
topics: [ data-structures, game, games ]

environment:
  sdk: ^3.4.4
  flutter: ">=3.10.0"  

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  meta: ^1.12.0
  

dev_dependencies:
  collection: ^1.18.0
  lints: ^3.0.0
  test: ^1.24.0
