name: fast_quadtree
description: A Dart package for creating and interacting with a quadtree data structure.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.4.4
  flutter: ">=3.10.0"  

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
